#
# ESPHome OTA Updates
#
# ESPHomeâ€™s Over-The-Air (OTA) platform allows you to remotely install modified/updated firmware
# binaries onto your ESPHome devices over their network (Wi-Fi or Ethernet) interface.
#
# https://esphome.io/components/ota/esphome
#

---
ota:
  - platform: esphome
    password: !secret base_ota_password
